spring:
  application:
    name: rocket-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: /home/ubuntu/app/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: tomcat
